language: rust
env:
  global:
    - secure: MnwPQuVBtlqmHFtJnrMzKJrZch55lE5S0wW/7CgCDeN/BLJQ/RNjEhjSqvF74s5PjIeR2k8Tiwi0CN73wnmFd9sqwPyZKGw6W/u+mC3rboVgrFOhHSQ9d3J21/xits5G1At2GvBqK5mZ6KJoLzgcHycpir7Cayrft1v0wxugo8o=
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  mv target/doc . &&
  curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
