env:
  global:
    - secure: ErMcr2VBkm8MlVg17TFDve8478AE3EOnr9FCV4LV43EHMKvy2QfI+kin9MEZ0iO/kI+ZYG2KM1MZkCEMNc7Yzk9hxrROYGUsUV9oYWkwbeP/KPRFodijiPNvbAWV7h5xEm5xKibfWgV+mqaAnqR0etQMMmWmuRnN5uRaDMFcVxI=
language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
