language: rust
env:
  global:
    - secure: "YzQ5jG9zQKzkSlMRvPJFOdFYeYb5bmKRjZwF7P7UcRtVqsoV0MsUTwJjqcknhu6BCtoCOsc6DCJXs9hLUxj+Lj5ChX5C1MQbcT8NWbxvoQy+GK0ynSPTvEPRVMjZf78xdu9PtnfdMj2b4kn3tN2Ps5A8tsSTk1WqUm3zLjd1ztA="
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=taskpipe/index.html>' > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
